# echo "Download cc100 data: $1:"
echo "Download cc25 data: $1:"
cat $1
echo "=========="
# cat $1 | parallel --gnu "wget {}"
wget --no-clobber  -w 20 -i  $1

# CC100
# <a href="http://data.statmt.org/cc-100/af.txt.xz">af</a> Afrikaans (305M)<br>
# <a href="http://data.statmt.org/cc-100/am.txt.xz">am</a> Amharic (133M)<br>
# <a href="http://data.statmt.org/cc-100/ar.txt.xz">ar</a> Arabic (5.4G)<br>
# <a href="http://data.statmt.org/cc-100/as.txt.xz">as</a> Assamese (7.6M)<br>
# <a href="http://data.statmt.org/cc-100/az.txt.xz">az</a> Azerbaijani (1.3G)<br>
# <a href="http://data.statmt.org/cc-100/be.txt.xz">be</a> Belarusian (692M)<br>
# <a href="http://data.statmt.org/cc-100/bg.txt.xz">bg</a> Bulgarian (9.3G)<br>
# <a href="http://data.statmt.org/cc-100/bn.txt.xz">bn</a> Bengali (860M)<br>
# <a href="http://data.statmt.org/cc-100/bn_rom.txt.xz">bn_rom</a> Bengali Romanized (164M)<br>
# <a href="http://data.statmt.org/cc-100/br.txt.xz">br</a> Breton (21M)<br>
# <a href="http://data.statmt.org/cc-100/bs.txt.xz">bs</a> Bosnian (18M)<br>
# <a href="http://data.statmt.org/cc-100/ca.txt.xz">ca</a> Catalan (2.4G)<br>
# <a href="http://data.statmt.org/cc-100/cs.txt.xz">cs</a> Czech (4.4G)<br>
# <a href="http://data.statmt.org/cc-100/cy.txt.xz">cy</a> Welsh (179M)<br>
# <a href="http://data.statmt.org/cc-100/da.txt.xz">da</a> Danish (12G)<br>
# <a href="http://data.statmt.org/cc-100/de.txt.xz">de</a> German (18G)<br>
# <a href="http://data.statmt.org/cc-100/el.txt.xz">el</a> Greek (7.4G)<br>
# <a href="http://data.statmt.org/cc-100/en.txt.xz">en</a> English (82G)<br>
# <a href="http://data.statmt.org/cc-100/eo.txt.xz">eo</a> Esperanto (250M)<br>
# <a href="http://data.statmt.org/cc-100/es.txt.xz">es</a> Spanish (14G)<br>
# <a href="http://data.statmt.org/cc-100/et.txt.xz">et</a> Estonian (1.7G)<br>
# <a href="http://data.statmt.org/cc-100/eu.txt.xz">eu</a> Basque (488M)<br>
# <a href="http://data.statmt.org/cc-100/fa.txt.xz">fa</a> Persian (20G)<br>
# <a href="http://data.statmt.org/cc-100/ff.txt.xz">ff</a> Fulah (3.1M)<br>
# <a href="http://data.statmt.org/cc-100/fi.txt.xz">fi</a> Finnish (15G)<br>
# <a href="http://data.statmt.org/cc-100/fr.txt.xz">fr</a> French (14G)<br>
# <a href="http://data.statmt.org/cc-100/fy.txt.xz">fy</a> Frisian (38M)<br>
# <a href="http://data.statmt.org/cc-100/ga.txt.xz">ga</a> Irish (108M)<br>
# <a href="http://data.statmt.org/cc-100/gd.txt.xz">gd</a> Scottish Gaelic (22M)<br>
# <a href="http://data.statmt.org/cc-100/gl.txt.xz">gl</a> Galician (708M)<br>
# </td><td valign="top">
# <a href="http://data.statmt.org/cc-100/gn.txt.xz">gn</a> Guarani (1.5M)<br>
# <a href="http://data.statmt.org/cc-100/gu.txt.xz">gu</a> Gujarati (242M)<br>
# <a href="http://data.statmt.org/cc-100/ha.txt.xz">ha</a> Hausa (61M)<br>
# <a href="http://data.statmt.org/cc-100/he.txt.xz">he</a> Hebrew (6.1G)<br>
# <a href="http://data.statmt.org/cc-100/hi.txt.xz">hi</a> Hindi (2.5G)<br>
# <a href="http://data.statmt.org/cc-100/hi_rom.txt.xz">hi_rom</a> Hindi Romanized (129M)<br>
# <a href="http://data.statmt.org/cc-100/hr.txt.xz">hr</a> Croatian (5.7G)<br>
# <a href="http://data.statmt.org/cc-100/ht.txt.xz">ht</a> Haitian (9.1M)<br>
# <a href="http://data.statmt.org/cc-100/hu.txt.xz">hu</a> Hungarian (15G)<br>
# <a href="http://data.statmt.org/cc-100/hy.txt.xz">hy</a> Armenian (776M)<br>
# <a href="http://data.statmt.org/cc-100/id.txt.xz">id</a> Indonesian (36G)<br>
# <a href="http://data.statmt.org/cc-100/ig.txt.xz">ig</a> Igbo (6.6M)<br>
# <a href="http://data.statmt.org/cc-100/is.txt.xz">is</a> Icelandic (779M)<br>
# <a href="http://data.statmt.org/cc-100/it.txt.xz">it</a> Italian (7.8G)<br>
# <a href="http://data.statmt.org/cc-100/ja.txt.xz">ja</a> Japanese (15G)<br>
# <a href="http://data.statmt.org/cc-100/jv.txt.xz">jv</a> Javanese (37M)<br>
# <a href="http://data.statmt.org/cc-100/ka.txt.xz">ka</a> Georgian (1.1G)<br>
# <a href="http://data.statmt.org/cc-100/kk.txt.xz">kk</a> Kazakh (889M)<br>
# <a href="http://data.statmt.org/cc-100/km.txt.xz">km</a> Khmer (153M)<br>
# <a href="http://data.statmt.org/cc-100/kn.txt.xz">kn</a> Kannada (360M)<br>
# <a href="http://data.statmt.org/cc-100/ko.txt.xz">ko</a> Korean (14G)<br>
# <a href="http://data.statmt.org/cc-100/ku.txt.xz">ku</a> Kurdish (90M)<br>
# <a href="http://data.statmt.org/cc-100/ky.txt.xz">ky</a> Kyrgyz (173M)<br>
# <a href="http://data.statmt.org/cc-100/la.txt.xz">la</a> Latin (609M)<br>
# <a href="http://data.statmt.org/cc-100/lg.txt.xz">lg</a> Ganda (7.3M)<br>
# <a href="http://data.statmt.org/cc-100/li.txt.xz">li</a> Limburgish (2.2M)<br>
# <a href="http://data.statmt.org/cc-100/ln.txt.xz">ln</a> Lingala (2.3M)<br>
# <a href="http://data.statmt.org/cc-100/lo.txt.xz">lo</a> Lao (63M)<br>
# <a href="http://data.statmt.org/cc-100/lt.txt.xz">lt</a> Lithuanian (3.4G)<br>
# <a href="http://data.statmt.org/cc-100/lv.txt.xz">lv</a> Latvian (2.1G)<br>
# </td><td valign="top">
# <a href="http://data.statmt.org/cc-100/mg.txt.xz">mg</a> Malagasy (29M)<br>
# <a href="http://data.statmt.org/cc-100/mk.txt.xz">mk</a> Macedonian (706M)<br>
# <a href="http://data.statmt.org/cc-100/ml.txt.xz">ml</a> Malayalam (831M)<br>
# <a href="http://data.statmt.org/cc-100/mn.txt.xz">mn</a> Mongolian (397M)<br>
# <a href="http://data.statmt.org/cc-100/mr.txt.xz">mr</a> Marathi (334M)<br>
# <a href="http://data.statmt.org/cc-100/ms.txt.xz">ms</a> Malay (2.1G)<br>
# <a href="http://data.statmt.org/cc-100/my.txt.xz">my</a> Burmese (46M)<br>
# <a href="http://data.statmt.org/cc-100/my_zaw.txt.xz">my_zaw</a> Burmese (Zawgyi) (178M)<br>
# <a href="http://data.statmt.org/cc-100/ne.txt.xz">ne</a> Nepali (393M)<br>
# <a href="http://data.statmt.org/cc-100/nl.txt.xz">nl</a> Dutch (7.9G)<br>
# <a href="http://data.statmt.org/cc-100/no.txt.xz">no</a> Norwegian (13G)<br>
# <a href="http://data.statmt.org/cc-100/ns.txt.xz">ns</a> Northern Sotho (1.8M)<br>
# <a href="http://data.statmt.org/cc-100/om.txt.xz">om</a> Oromo (11M)<br>
# <a href="http://data.statmt.org/cc-100/or.txt.xz">or</a> Oriya (56M)<br>
# <a href="http://data.statmt.org/cc-100/pa.txt.xz">pa</a> Punjabi (90M)<br>
# <a href="http://data.statmt.org/cc-100/pl.txt.xz">pl</a> Polish (12G)<br>
# <a href="http://data.statmt.org/cc-100/ps.txt.xz">ps</a> Pashto (107M)<br>
# <a href="http://data.statmt.org/cc-100/pt.txt.xz">pt</a> Portuguese (13G)<br>
# <a href="http://data.statmt.org/cc-100/qu.txt.xz">qu</a> Quechua (1.5M)<br>
# <a href="http://data.statmt.org/cc-100/rm.txt.xz">rm</a> Romansh (4.8M)<br>
# <a href="http://data.statmt.org/cc-100/ro.txt.xz">ro</a> Romanian (16G)<br>
# <a href="http://data.statmt.org/cc-100/ru.txt.xz">ru</a> Russian (46G)<br>
# <a href="http://data.statmt.org/cc-100/sa.txt.xz">sa</a> Sanskrit (44M)<br>
# <a href="http://data.statmt.org/cc-100/si.txt.xz">si</a> Sinhala (452M)<br>
# <a href="http://data.statmt.org/cc-100/sc.txt.xz">sc</a> Sardinian (143K)<br>
# <a href="http://data.statmt.org/cc-100/sd.txt.xz">sd</a> Sindhi (67M)<br>
# <a href="http://data.statmt.org/cc-100/sk.txt.xz">sk</a> Slovak (6.1G)<br>
# <a href="http://data.statmt.org/cc-100/sl.txt.xz">sl</a> Slovenian (2.8G)<br>
# <a href="http://data.statmt.org/cc-100/so.txt.xz">so</a> Somali (78M)<br>
# <a href="http://data.statmt.org/cc-100/sq.txt.xz">sq</a> Albanian (1.3G)<br>
# </td><td valign="top">
# <a href="http://data.statmt.org/cc-100/sr.txt.xz">sr</a> Serbian (1.5G)<br>
# <a href="http://data.statmt.org/cc-100/ss.txt.xz">ss</a> Swati (86K)<br>
# <a href="http://data.statmt.org/cc-100/su.txt.xz">su</a> Sundanese (15M)<br>
# <a href="http://data.statmt.org/cc-100/sv.txt.xz">sv</a> Swedish (21G)<br>
# <a href="http://data.statmt.org/cc-100/sw.txt.xz">sw</a> Swahili (332M)<br>
# <a href="http://data.statmt.org/cc-100/ta.txt.xz">ta</a> Tamil (1.3G)<br>
# <a href="http://data.statmt.org/cc-100/ta_rom.txt.xz">ta_rom</a> Tamil Romanized (68M)<br>
# <a href="http://data.statmt.org/cc-100/te.txt.xz">te</a> Telugu (536M)<br>
# <a href="http://data.statmt.org/cc-100/te_rom.txt.xz">te_rom</a> Telugu Romanized (79M)<br>
# <a href="http://data.statmt.org/cc-100/th.txt.xz">th</a> Thai (8.7G)<br>
# <a href="http://data.statmt.org/cc-100/tl.txt.xz">tl</a> Tagalog (701M)<br>
# <a href="http://data.statmt.org/cc-100/tn.txt.xz">tn</a> Tswana (8.0M)<br>
# <a href="http://data.statmt.org/cc-100/tr.txt.xz">tr</a> Turkish (5.4G)<br>
# <a href="http://data.statmt.org/cc-100/ug.txt.xz">ug</a> Uyghur (46M)<br>
# <a href="http://data.statmt.org/cc-100/uk.txt.xz">uk</a> Ukrainian (14G)<br>
# <a href="http://data.statmt.org/cc-100/ur.txt.xz">ur</a> Urdu (884M)<br>
# <a href="http://data.statmt.org/cc-100/ur_rom.txt.xz">ur_rom</a> Urdu Romanized (141M)<br>
# <a href="http://data.statmt.org/cc-100/uz.txt.xz">uz</a> Uzbek (155M)<br>
# <a href="http://data.statmt.org/cc-100/vi.txt.xz">vi</a> Vietnamese (28G)<br>
# <a href="http://data.statmt.org/cc-100/wo.txt.xz">wo</a> Wolof (3.6M)<br>
# <a href="http://data.statmt.org/cc-100/xh.txt.xz">xh</a> Xhosa (25M)<br>
# <a href="http://data.statmt.org/cc-100/yi.txt.xz">yi</a> Yiddish (51M)<br>
# <a href="http://data.statmt.org/cc-100/yo.txt.xz">yo</a> Yoruba (1.1M)<br>
# <a href="http://data.statmt.org/cc-100/zh-Hans.txt.xz">zh-Hans</a> Chinese (Simplified) (14G)<br>
# <a href="http://data.statmt.org/cc-100/zh-Hant.txt.xz">zh-Hant</a> Chinese (Traditional) (5.3G)<br>
# <a href="http://data.statmt.org/cc-100/zu.txt.xz">zu</a> Zulu (4.3M)<br>


